package com.example.orm.enums;

public enum ItemTypeEnums {
    TINYINT,SMALLINT,INTEGER,BIGINT,FLOAT,DOUBLE,DECIMAL,
    DATE,TIME,YEAR,DATETIME,TIMESTAMP,
    CHAR,VARCHAR,TINYBLOB,TINYTEXT,BLOB,TEXT,MEDIUMBLOB,MEDIUMTEXT,LONGBLOB,LONGTEXT;
}
